# These are supported funding model platforms

ko_fi: cyborgninja
# You can also add other platforms:
# github: [your-github-username]
# patreon: your-patreon-username
# custom: ["https://your-donation-link.com"]
